CREATE TABLE IF NOT EXISTS APP_USER
(
    ID   UUID NOT NULL PRIMARY KEY,
    NAME TEXT NOT NULL
);

CREATE TABLE CODE_REPOSITORY
(
    ID         UUID PRIMARY KEY,
    USER_ID    UUID                     NOT NULL,
    NAME       TEXT                     NOT NULL,
    LANGUAGE   TEXT                     NOT NULL,
    STAR_COUNT BIGINT DEFAULT 0,
    FORK_COUNT BIGINT DEFAULT 0,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
